ant-design/ant-design-pro-layout

src/utils/getBreadcrumbProps.tsx

修复过滤breadcrumb item时没有填充component

bugfix breadcrumb params

---

src/Footer.tsx
src/index.tsx

now the footer used by basic layout could not be modified, so export global footer component to make footer configurable

export global footer component to make footer configurable

---

src/PageHeaderWrapper/index.less

Fix extra margin bottom

---

README.md
README.zh-CN.md
example/src/layouts/BasicLayout.tsx
src/BasicLayout.tsx
src/SiderMenu/SiderMenu.tsx

BasicLayoutProps添加--disableMobile：是否禁用移动端模式
SiderMenuProps添加——menuProps要传给antd的menu组件的props

是否禁用移动端模式，可从外部传props给antd的menu

---

src/SiderMenu/BaseMenu.tsx

https://github.com/ant-design/ant-design-pro-layout/issues/138

Add onTitleClick for subMenu

---

README.md
README.zh-CN.md

docs(fix reautoHideHeader type in readme):

---

README.md
example/src/components/GlobalHeader/RightContent.tsx
example/src/layouts/BasicLayout.tsx
src/BasicLayout.tsx
src/GridContent/index.tsx
src/Header.tsx
src/SiderMenu/BaseMenu.tsx
src/SiderMenu/SiderMenu.tsx
src/SiderMenu/index.less
src/TopNavHeader/index.tsx
src/defaultSettings.ts

add: add bothmenu layout, with header and sider navigation(#65)

---

README.md
example/src/components/GlobalHeader/RightContent.tsx
example/src/layouts/BasicLayout.tsx
src/BasicLayout.tsx
src/GridContent/index.tsx
src/Header.tsx
src/SiderMenu/BaseMenu.tsx
src/SiderMenu/SiderMenu.tsx
src/SiderMenu/index.less
src/TopNavHeader/index.tsx
src/defaultSettings.ts

Reverts ant-design/ant-design-pro-layout#151
PR 审核不够仔细，这个api 有点麻烦了
通过layout 嵌套的方式才是最好。
```
<ProLayout>
<ProLayout />
</ProLayout>
```

 🙇‍♂️  🙇‍♂️  🙇‍♂️ Revert "add: add bothmenu layout, with header and sider navigation(#65)"

---

README.md
README.zh-CN.md
example/src/layouts/BasicLayout.tsx
src/SiderMenu/SiderMenu.tsx

breakpoint 配置为 false 的情况下，collapsed 将会一直生效

✨ feat: Support disable breakpoint

---

package.json

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
https://zh-hans.reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react
hook 调用需要保证 react 为同一实例。

move react & react-dom to devDependencies

---

src/index.tsx

close https://github.com/ant-design/ant-design-pro-layout/issues/163

:zap:  暴露TopNavHeader组件

---

example/src/typings.d.ts
src/BasicLayout.tsx
src/Footer.tsx
src/GlobalFooter/index.tsx
src/GlobalHeader/index.tsx
src/GridContent/index.tsx
src/Header.tsx
src/PageHeaderWrapper/index.tsx
src/SiderMenu/SiderMenu.tsx
src/SiderMenu/index.tsx
src/TopNavHeader/index.tsx

为了方便自定义，每个组件都增加了 className 和 style 的支持

✨ feat: all component support style and className 

---

src/BasicLayout.tsx

close https://github.com/ant-design/ant-design-pro/issues/5575

fix two renders of Layout

---

src/Footer.tsx

`copyright` 支持传入`false`而不显示`copyright`。

copyright support false

---

example/src/components/GlobalHeader/index.less
example/src/layouts/BasicLayout.tsx
src/GlobalHeader/index.tsx
src/SiderMenu/index.tsx

🤒fix : fix mobile style error

---

README.md
README.zh-CN.md
example/config/defaultSettings.ts
example/src/pages/Welcome.tsx
src/BasicLayout.less
src/Header.tsx
src/SettingDrawer/index.tsx
src/defaultSettings.ts
tests/__tests__/__snapshots__/settingDrawer.test.tsx.snap
tests/__tests__/defaultSettings.ts

-  rm autoHideHeader
-  fix fixed header problem
-----
- 删除了 autoHideHeader 
- 使用了 sticky 来实现 fixedHeader ，效果更好

feat: rm autoHideHeader and fix fixedHeader problem

---

.stories/index.stories.tsx
src/PageHeaderWrapper/index.tsx

feat: add tabAnimated props

---

src/SiderMenu/index.tsx

修复手机版下菜单错位，#239
@afc163 这个是用了bodyStyle的

bugifx: fix mobile menu

---

example/config/config.ts
src/BasicLayout.less
src/TopNavHeader/index.tsx

fix https://github.com/ant-design/ant-design-pro/issues/5764

bugfix: fix the problem that the top menu bar is not responsive

---

.eslintrc.js
example/config/config.ts
example/src/layouts/BasicLayout.tsx
example/src/layouts/BlankLayout.tsx
example/src/pages/AccountSettings/index.tsx
example/src/pages/FlexDemo.tsx
example/src/pages/Welcome.tsx
package.json
src/BasicLayout.less
src/BasicLayout.tsx
src/Header.tsx
src/TopNavHeader/index.tsx
src/WrapContent.tsx

继续使用 position: fixed; 来实现功能 固定头和菜单的功能，在不嵌套 layout 的情况下表现完美。
嵌套情况下 固定 siderMenu 和 header 必须同时使用，不然会有一些需要手动设置的地方。
antd trigger 的问题 ，通过 ConfigProvider 来重定向一下解决问题。

bugfix：Remove some hack code

---

README.md
README.zh-CN.md
src/BasicLayout.tsx
tests/__tests__/index.test.tsx

每次切换页面都会触发一下
```jsx
onPageChange={(location)=>{
console.log(location)
}}
```

✨ feature: support onPageChange props

---

example/src/layouts/BasicLayout.tsx
package.json
src/TopNavHeader/index.tsx
src/WrapContent.tsx
src/utils/utils.ts

close https://github.com/ant-design/ant-design-pro/issues/6143

🐛 bug: Fix setState issues caused by debounce

---

.github/workflows/test.yml
package.json
tsconfig.json

✅ tests: add tsc check

---

example/config/config.ts
src/typings.ts
src/utils/getMenuData.ts

✨ features: support menuItem.locale=false

---

README.md
README.zh-CN.md
docs/api.md
docs/demo/api.tsx
docs/index.md
package.json
src/BasicLayout.tsx
tests/__tests__/index.test.tsx

💥 feat: Support for pure mode

---

package.json
src/BasicLayout.tsx
src/PageHeaderWrapper/index.tsx
src/utils/hooks.ts

close https://github.com/ant-design/ant-design-pro/issues/6227

🐛 bug: useDocumentTitle replace  react-helmet-async

---

example/src/layouts/BasicLayout.tsx
src/TopNavHeader/index.less

close https://github.com/ant-design/ant-design-pro-layout/issues/388

🐛 bug: fix menu not adapting to size

---

src/SettingDrawer/index.less
src/SettingDrawer/index.tsx

ref https://github.com/ant-design/ant-design-pro/issues/6186

💄 UI:better dark theme

---

example/src/layouts/BasicLayout.tsx
src/SettingDrawer/index.less
src/SiderMenu/index.less
src/TopNavHeader/index.tsx
src/WrapContent.tsx
tests/__tests__/__snapshots__/index.test.tsx.snap
tests/__tests__/__snapshots__/pageHeaderWarp.test.tsx.snap

close https://github.com/ant-design/ant-design-pro/issues/6311

💄 UI: Fix the wrong calculation of the content width on the right

---

src/SiderMenu/SiderMenu.tsx

折叠按钮收缩时，不弹出标题

---

docs/demo/base.tsx
src/TopNavHeader/index.tsx

🐛 bug: rightContentRender default have a div

---

src/SiderMenu/BaseMenu.tsx

fix: 外部链接菜单项多了一个空格

---

docs/example/complexMenu.ts
src/SiderMenu/BaseMenu.tsx
tests/__tests__/__snapshots__/index.test.tsx.snap
tests/__tests__/footer.test.tsx
tests/__tests__/index.test.tsx
tests/__tests__/util.ts

close https://github.com/ant-design/ant-design-pro-layout/issues/494

🐛 bug: fix menu children all hideInMenu bug

---

package.json
src/SiderMenu/BaseMenu.tsx
tests/__tests__/__snapshots__/index.test.tsx.snap
tests/__tests__/index.test.tsx
tsconfig-check.json
tsconfig.json

close https://github.com/ant-design/ant-design-pro-layout/issues/524

🐛 bug: fix menuData no work error

---

src/SiderMenu/BaseMenu.tsx

close https://github.com/ant-design/ant-design-pro/issues/6992

🐛 bug: fix hideChildrenInMenu no work for menuItemRender

---

src/WrapContent.tsx

🐛 bug: remove ConfigProvider

---

src/SiderMenu/BaseMenu.tsx
tests/__tests__/__snapshots__/index.test.tsx.snap
tests/__tests__/__snapshots__/pageHeaderWarp.test.tsx.snap

close https://github.com/ant-design/ant-design-pro-layout/issues

🐛 bug: fix openkeys error in defaultOpenKeys

---

src/SiderMenu/BaseMenu.tsx
tests/__tests__/__snapshots__/settingDrawer.test.tsx.snap

🐛 bug: fix menudata not using the latest version
